# Generated by Django 6.1 on 2026-09-05 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_code', models.CharField(help_text='Unique corridor shipment identifier (e.g. RSQ-102)', max_length=40, unique=True)),
                ('cargo_type', models.CharField(choices=[('MEDICINE', 'Critical Medicine & Vaccines'), ('FOOD', 'Emergency Rations & Potable Water'), ('RELIEF', 'Disaster Relief Supplies & Tents'), ('DISASTER_AID', 'Rescue Gear & Power Generators'), ('GENERAL', 'General Cargo')], default='MEDICINE', max_length=40)),
                ('cargo_priority', models.CharField(choices=[('CRITICAL', 'Critical Priority (Life-Saving)'), ('HIGH', 'High Priority (Expedited Dispatch)'), ('NORMAL', 'Standard Priority')], default='CRITICAL', max_length=30)),
                ('origin', models.CharField(help_text='Dispatch origin location (e.g. Guwahati Central Medical Hub)', max_length=150)),
                ('destination', models.CharField(help_text='Delivery destination (e.g. Silchar Civil Hospital)', max_length=150)),
                ('weight_kg', models.FloatField(default=500.0, help_text='Total shipment cargo weight in kilograms')),
                ('delivery_address', models.TextField(blank=True, help_text='Specific street/district delivery address')),
                ('special_instructions', models.TextField(blank=True, help_text='Handling guidelines (e.g. Cold-chain refrigeration required)')),
                ('status', models.CharField(choices=[('READY', 'Ready for Dispatch'), ('ASSIGNED', 'Assigned to Field Driver'), ('IN_TRANSIT', 'In-Transit on Corridor'), ('DELIVERED', 'Delivered & Verified'), ('CANCELLED', 'Cancelled')], default='READY', max_length=30)),
                ('is_emergency_relief', models.BooleanField(default=True, help_text='Priority corridor clearance for MDoNER / NDMA relief')),
                ('risk_score', models.IntegerField(default=24, help_text='Corridor hazard composite score (0-100)')),
                ('risk_level', models.CharField(choices=[('SAFE', 'Safe Corridor (< 35)'), ('CAUTION', 'Cautionary Alert (35 - 69)'), ('BLOCKED', 'High Risk / Blocked (≥ 70)')], default='SAFE', max_length=20)),
                ('risk_summary', models.TextField(blank=True, help_text='AI explainability summary of route safety')),
                ('risk_factors', models.JSONField(blank=True, default=list, help_text='Bullet points explaining why route was scored this way')),
                ('recommended_route', models.CharField(blank=True, help_text='Primary corridor or alternate ridge reroute', max_length=255)),
                ('qr_token', models.CharField(help_text='Unique cryptographic token encoded into Driver QR badge', max_length=64, unique=True)),
                ('qr_svg', models.TextField(blank=True, help_text='Inline SVG / Data URL for driver scanning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='User/Organization who requisitioned this shipment', on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_code', models.CharField(help_text='Trip activation identifier (e.g. TRIP-102)', max_length=40, unique=True)),
                ('vehicle_number', models.CharField(default='TR-102', help_text='Assigned vehicle plate', max_length=50)),
                ('vehicle_type', models.CharField(default='Heavy Emergency Truck (6-10W)', help_text='Vehicle capacity spec', max_length=60)),
                ('status', models.CharField(choices=[('READY', 'Pending QR Activation'), ('ACTIVE', 'Trip Active (Departed Base)'), ('IN_TRANSIT', 'In-Transit on Mountain Pass'), ('COMPLETED', 'Trip Completed & Reached')], default='READY', max_length=30)),
                ('current_corridor_segment', models.CharField(default='Guwahati Outskirts (NH-27 Junction)', help_text='Live physical road segment ID', max_length=150)),
                ('activated_at', models.DateTimeField(blank=True, help_text='Timestamp when driver scanned and verified QR code', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, help_text='Field driver assigned to this trip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='logistics.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
