# Generated by Django 6.1 on 2026-09-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='last_ping_at',
            field=models.DateTimeField(blank=True, help_text='Last telemetry or checkpoint check-in', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='route_advisory',
            field=models.TextField(blank=True, default='Proceed with standard mountain driving precautions.', help_text='Driver-specific advisory based on AI terrain assessment'),
        ),
    ]
