# Generated by Django 6.1 on 2026-09-04 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='area_type',
            field=models.CharField(choices=[('CITY', 'City / Urban'), ('VILLAGE', 'Village / Rural')], default='CITY', help_text='Urban city vs rural village locality', max_length=20),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='locality_name',
            field=models.CharField(blank=True, help_text='City or Village name', max_length=150),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='pincode',
            field=models.CharField(blank=True, help_text='6-digit postal code', max_length=10),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='state',
            field=models.CharField(blank=True, help_text='North Eastern state jurisdiction', max_length=50),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='license_expiry',
            field=models.DateField(blank=True, help_text='License expiry date', null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='license_issuing_state',
            field=models.CharField(blank=True, help_text='State where driving license was issued', max_length=50),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_type',
            field=models.CharField(default='Heavy Emergency Truck', help_text='Truck or cargo vehicle specification', max_length=60),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='license_number',
            field=models.CharField(help_text='Official driving license or driver ID (e.g. TN01 20190001234)', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('DRIVER', 'Field Driver'), ('ADMIN', 'Government Official / Authority')], default='CUSTOMER', help_text='Role-based access level for ResQRoute', max_length=20),
        ),
        migrations.CreateModel(
            name='AuthorityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_id', models.CharField(help_text='Official Government Employee ID or Service Badge Code (e.g. MDoNER-AS-102)', max_length=60)),
                ('designation', models.CharField(help_text='Official government rank or title (e.g. District Disaster Management Officer)', max_length=150)),
                ('department_name', models.CharField(help_text='Government agency or ministry (e.g. MDoNER, ASDMA, BRO, NDRF)', max_length=150)),
                ('jurisdiction_state', models.CharField(help_text='State or regional jurisdiction across North Eastern corridor', max_length=50)),
                ('office_address', models.TextField(blank=True, help_text='Official government office or district headquarters address')),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending Superadmin Approval'), ('APPROVED', 'Approved / Verified Authority'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Verification status by central developer/superadmin', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Superadmin who verified this authority', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_authorities', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authority_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
