# Generated by Django 6.1 on 2026-09-04 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customerprofile_area_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorityprofile',
            name='district_office',
            field=models.CharField(blank=True, help_text='District office or regional jurisdiction (Optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='district',
            field=models.CharField(blank=True, help_text='District location', max_length=100),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='district',
            field=models.CharField(blank=True, help_text='Operating or registered district', max_length=100),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='state',
            field=models.CharField(blank=True, help_text='Operating or registered state', max_length=50),
        ),
        migrations.CreateModel(
            name='OfficialPasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_id', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Superadmin Approval'), ('APPROVED', 'Approved / Verified Authority'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('temp_password', models.CharField(blank=True, max_length=128)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_password_resets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
